global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'ecs-services'
    static_configs:
      - targets:
          - 'worker.voting-app.local:1234'
          - 'result.voting-app.local:80'
          - 'db.voting-app.local:9187'
          - 'vote.voting-app.local:80'